### ISSUE TITLE
java.lang.IllegalArgumentException: End gap 8 is too big: capacity is 7

### ISSUE THREAD

**Issue by yschimke** [rsocket/rsocket-kotlin#134]
## Actual Behavior

```
Exception in thread "DefaultDispatcher-worker-3" java.lang.IllegalArgumentException: End gap 8 is too big: capacity is 7
	at io.ktor.utils.io.core.BufferKt.endGapReservationFailedDueToCapacity(Buffer.kt:463)
	at io.ktor.utils.io.core.Buffer.reserveEndGap(Buffer.kt:220)
	at io.ktor.utils.io.core.AbstractOutput.appendNewChunk(AbstractOutput.kt:195)
	at io.ktor.utils.io.core.AbstractOutput.prepareWriteHead(AbstractOutput.kt:497)
	at io.ktor.utils.io.core.OutputPrimitivesKt.writeIntFallback(OutputPrimitives.kt:133)
	at io.ktor.utils.io.core.OutputPrimitivesKt.writeInt(OutputPrimitives.kt:22)
	at io.rsocket.kotlin.frame.Frame.toPacket(Frame.kt:41)
	at io.rsocket.kotlin.ConnectionKt.sendFrame(Connection.kt:42)
	at io.rsocket.kotlin.internal.RSocketState$start$3.invokeSuspend(RSocketState.kt:197)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.selects.SelectBuilderImpl.resumeWith(Select.kt:302)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
java.util.concurrent.CancellationException: Connection closed
	at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:22)
	at io.rsocket.kotlin.internal.RSocketState$start$2.invoke(RSocketState.kt:183)
	at io.rsocket.kotlin.internal.RSocketState$start$2.invoke(RSocketState.kt:33)
	at kotlinx.coroutines.InvokeOnCompletion.invoke(JobSupport.kt:1412)
	at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1544)
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:326)
	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:241)
	at kotlinx.coroutines.JobSupport.continueCompleting(JobSupport.kt:951)
	at kotlinx.coroutines.JobSupport.access$continueCompleting(JobSupport.kt:29)
	at kotlinx.coroutines.JobSupport$ChildCompletion.invoke(JobSupport.kt:1175)
	at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1544)
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:326)
	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:241)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:922)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:875)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:840)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.selects.SelectBuilderImpl.resumeWith(Select.kt:302)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.IllegalArgumentException: End gap 8 is too big: capacity is 7
	at io.ktor.utils.io.core.BufferKt.endGapReservationFailedDueToCapacity(Buffer.kt:463)
	at io.ktor.utils.io.core.Buffer.reserveEndGap(Buffer.kt:220)
	at io.ktor.utils.io.core.AbstractOutput.appendNewChunk(AbstractOutput.kt:195)
	at io.ktor.utils.io.core.AbstractOutput.prepareWriteHead(AbstractOutput.kt:497)
	at io.ktor.utils.io.core.OutputPrimitivesKt.writeIntFallback(OutputPrimitives.kt:133)
	at io.ktor.utils.io.core.OutputPrimitivesKt.writeInt(OutputPrimitives.kt:22)
	at io.rsocket.kotlin.frame.Frame.toPacket(Frame.kt:41)
	at io.rsocket.kotlin.ConnectionKt.sendFrame(Connection.kt:42)
	at io.rsocket.kotlin.internal.RSocketState$start$3.invokeSuspend(RSocketState.kt:197)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	... 7 more
```

## Steps to Reproduce

With 

./rsocket-cli ws://rsocket-demo-1.ew.r.appspot.com/rsocket
./rsocket-cli wss://rsocket-demo-1.ew.r.appspot.com/rsocket

## Your Environment

GraalVM (11) or JDK11

**Comment by yschimke** [comment]
Happens much sooner with keepalive=1

```
 rsocket-cli wss://rsocket-demo-1.ew.r.appspot.com/rsocket --keepalive=1
0
Exception in thread "DefaultDispatcher-worker-3" java.lang.IllegalArgumentException: End gap 8 is too big: capacity is 7
	at io.ktor.utils.io.core.BufferKt.endGapReservationFailedDueToCapacity(Buffer.kt:463)
	at io.ktor.utils.io.core.Buffer.reserveEndGap(Buffer.kt:220)
	at io.ktor.utils.io.core.AbstractOutput.appendNewChunk(AbstractOutput.kt:195)
	at io.ktor.utils.io.core.AbstractOutput.prepareWriteHead(AbstractOutput.kt:497)
	at io.ktor.utils.io.core.OutputPrimitivesKt.writeIntFallback(OutputPrimitives.kt:133)
	at io.ktor.utils.io.core.OutputPrimitivesKt.writeInt(OutputPrimitives.kt:22)
```

**Comment by whyoleg** [comment]
Looks similar to https://youtrack.jetbrains.com/issue/KTOR-960
So I think, it's ktor-io issue
I have failed to create some minimal reproducible code for this

**Comment by yschimke** [comment]
```
#!/usr/bin/env kotlin

@file:Repository("https://repo1.maven.org/maven2/")
@file:Repository("https://jcenter.bintray.com/")
@file:DependsOn("io.rsocket.kotlin:rsocket-core:0.12.0")
@file:DependsOn("io.rsocket.kotlin:rsocket-core-jvm:0.12.0")
@file:DependsOn("io.rsocket.kotlin:rsocket-transport-ktor:0.12.0")
@file:DependsOn("io.rsocket.kotlin:rsocket-transport-ktor-jvm:0.12.0")
@file:DependsOn("io.rsocket.kotlin:rsocket-transport-ktor-client:0.12.0")
@file:DependsOn("io.rsocket.kotlin:rsocket-transport-ktor-client-jvm:0.12.0")
@file:DependsOn("io.ktor:ktor-client-okhttp:1.4.3")
@file:CompilerOptions("-jvm-target", "1.8", "-Xopt-in=kotlin.RequiresOptIn")
@file:OptIn(ExperimentalTime::class)

import io.ktor.client.HttpClient
import io.ktor.client.engine.okhttp.OkHttp
import io.ktor.client.features.websocket.WebSockets
import io.rsocket.kotlin.RSocket
import io.rsocket.kotlin.core.RSocketConnector
import io.rsocket.kotlin.keepalive.KeepAlive
import io.rsocket.kotlin.payload.Payload
import io.rsocket.kotlin.payload.PayloadMimeType
import io.rsocket.kotlin.transport.ktor.client.RSocketSupport
import io.rsocket.kotlin.transport.ktor.client.rSocket
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.collect
import kotlinx.coroutines.flow.take
import kotlinx.coroutines.runBlocking
import kotlin.time.ExperimentalTime
import kotlin.time.seconds

runBlocking {
  val client = HttpClient(OkHttp) {
    install(WebSockets)
    install(RSocketSupport) {
      connector = RSocketConnector {
        connectionConfig {
          // setupPayload(setupPayload)
          keepAlive = KeepAlive(5.seconds)
          payloadMimeType = PayloadMimeType("application/json", "application/json")
        }
      }
    }
  }

  // connect to some url
  val rSocket: RSocket = client.rSocket("wss://rsocket-demo.herokuapp.com/rsocket")

  // request stream
  val stream: Flow<Payload> = rSocket.requestStream(Payload.Empty)

  // take 5 values and print response
  stream.take(5).collect { payload: Payload ->
    println(payload.data.readText())
  }
}
```

**Comment by 5V715** [comment]
facing the same issue. any news here ?

**Comment by whyoleg** [comment]
commented in KTOR youtrack: https://youtrack.jetbrains.com/issue/KTOR-960
Will see how it goes there and will spend more time for investigation on my own

**Comment by whyoleg** [comment]
I've found a way to fix this issue (Will create PR soon), but Im still thinking that it's ktor-io issue

**Comment by whyoleg** [comment]
from youtrack: will be fixed in ktor-io 1.5.3

**Comment by whyoleg** [comment]
Note: issue fixed only inside rsocket-kotlin internal WS transport implementation. If the user will put `ByteReadPacket`'s in `Payload` created with another pool (f.e. using just `ByteReadPacket` constructor) same issue can happen until the issue will be fixed in `ktor-io`

**Comment by 5V715** [comment]
when is the next released version that contains the fix or is there some nightly i can use. didn't find anything in the documentation. 🙇

**Comment by whyoleg** [comment]
snapshot can be retrieved with repository https://oss.jfrog.org/oss-snapshot-local and version 0.13.0-SNAPSHOT
