### ISSUE TITLE
Document that rsocket-transport-netty not Android compatible

### ISSUE THREAD

**Issue by yschimke** [rsocket/rsocket-kotlin#44]
Hit this issue

```
> Task :app:transformClassesWithStackFramesFixerForDebug
Exception in thread "main" java.lang.IllegalStateException: Couldn't load java/util/concurrent/Flow$Subscription, is the classpath complete?
	at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.loadFromInternal(DefaultMethodClassFixer.java:223)
	at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.stubMissingDefaultAndBridgeMethods(DefaultMethodClassFixer.java:201)
	at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.visitEnd(DefaultMethodClassFixer.java:95)
	at org.objectweb.asm.ClassVisitor.visitEnd(ClassVisitor.java:339)
	at com.google.devtools.build.android.desugar.InterfaceDesugaring.visitEnd(InterfaceDesugaring.java:112)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:702)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
	at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:477)
	at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:361)
	at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:314)
	at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:711)
Caused by: java.lang.ClassNotFoundException: Class java.util.concurrent.Flow$Subscription not found
	at com.google.devtools.build.android.desugar.HeaderClassLoader.findClass(HeaderClassLoader.java:53)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.loadFromInternal(DefaultMethodClassFixer.java:221)
	... 10 more
```

Seems to be because of io.projectreactor.ipc:reactor-netty:0.7.8.RELEASE obviously depends on reactor-core which has reactor.adapter.JdkFlowAdapter.  Not sure if this is intentional, but seems unfortunate given the name used to be rsocket-android, and kotlin gives you good support back to 1.6 and early android.

**Comment by mostroverkhov** [comment]
This transport was added specifically for java8+. If this does not work on mobile for java8, then It has to be resolved. Otherwise there is okhttp transport. If reactor-netty transport would work for pre java8, there would be no need to mess with okhttp (which offers rather questionable websockets APIs btw)

**Comment by yschimke** [comment]
How can we improve the websocket support in OkHttp?  What would make it better for this case? OkHttp isn't a toolkit like Netty, so the common client cases are generally optimised for.

**Comment by yschimke** [comment]
I'm ok with that direction, not worth wasting time over.  But maybe worth calling out in the top level docs.  I think it pretty much rules on the netty transports on Android for another couple of years.

**Comment by mostroverkhov** [comment]
Update on readme would work I think: it has `Transport` section where this can be explicitly called out.

**Comment by mostroverkhov** [comment]
reactor-netty based transport converted to internal for testing purposes only
