### ISSUE TITLE
OutOfDirectMemoryError when trying to test back pressure

### ISSUE THREAD

**Issue by ration** [rsocket/rsocket-kotlin#51]
Hi, 

While creating a demo with RSockets that does backpressure, I noticed that netty chokes if there's too much data to deliver and the client doesn't answer. The setup is Spring Boot with rsocket-kotlin on the back end that pumps messages as fast as it can through a websocket to a angular front via rsocket-js. I can observe that there's backpressure caused drops, but once the browser slows down enough and the error below happens. With Firefox rather quickly.

The demo can be found at [https://github.com/ration/ticker-demo](https://github.com/ration/ticker-demo)
I just started to smoke out RSockets, so feel free to say if the example is just dumb.

`io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 3456106503, max: 3464495104)
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:69)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 3456106503, max: 3464495104)
	at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:640)
	at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:594)
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:764)
	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:740)
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:244)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:226)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:146)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:324)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:176)
	at io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:113)
	at io.rsocket.kotlin.Frame$PayloadFrame.from(Frame.kt:548)
	at io.rsocket.kotlin.Frame$PayloadFrame.from(Frame.kt:537)
	at io.rsocket.kotlin.Frame$PayloadFrame.from$default(Frame.kt:534)
	at io.rsocket.kotlin.internal.RSocketResponder$handleStream$1.apply(RSocketResponder.kt:201)
	at io.rsocket.kotlin.internal.RSocketResponder$handleStream$1.apply(RSocketResponder.kt:40)
	at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:63)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:407)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.internal.schedulers.ImmediateThinScheduler$ImmediateThinWorker.schedule(ImmediateThinScheduler.java:89)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.trySchedule(FlowableObserveOn.java:166)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.onNext(FlowableObserveOn.java:117)
	at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:68)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:407)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	... 8 more
Exception in thread "RxCachedThreadScheduler-1" io.reactivex.exceptions.UndeliverableException: The exception coul`

**Comment by mostroverkhov** [comment]
@ration Hello, and thanks for report. RSocket-kotlin is still in development, and backpressure related issues are very likely.I will look on what the cause may be, and return to you later this weekend.

**Comment by mostroverkhov** [comment]
@ration One thing worth a try is avoiding large `requestN` over network: https://github.com/ration/ticker-demo/blob/eabdb93a32d4fc7fed88f0ead83b5c809d56f5bf/src/main/webapp/src/app/ticker-service.ts#L66. Request moderate value in `onSubscribe` (e.g. 32) and save `subscription`, then keep requesting in `onNext` once you receive enough items.

**Comment by ration** [comment]
Ahh that helped, thanks! I didn't quite fully understand what that value did, I just took it from the javascript example.  Now that I re-read the spec regarding the request-n, it makes sense now.

**Comment by ration** [comment]
For anyone curious, this was for an post I wrote about backpressure on  [medium](https://medium.com/@lahtela/dynamic-flow-control-during-backpressure-with-rxjava-and-rsockets-41e369cda122
)

Comments are welcome :)
