### ISSUE TITLE
GraalVM native-image support broken due to Payload

### ISSUE THREAD

**Issue by yschimke** [rsocket/rsocket-kotlin#77]
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:290)
	at java.lang.Class.ensureInitialized(DynamicHub.java:499)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:235)
	at java.lang.Class.ensureInitialized(DynamicHub.java:499)
	at io.ktor.utils.io.core.IoBuffer.<clinit>(IoBufferJVM.kt:469)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
	at java.lang.Class.ensureInitialized(DynamicHub.java:499)
	at io.ktor.utils.io.core.internal.ChunkBuffer$Companion.getEmpty(ChunkBuffer.kt:151)
	at io.ktor.utils.io.core.ByteReadPacket.<clinit>(ByteReadPacket.kt:46)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
	at java.lang.Class.ensureInitialized(DynamicHub.java:499)
	at io.rsocket.kotlin.payload.Payload.<clinit>(Payload.kt:26)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
	at java.lang.Class.ensureInitialized(DynamicHub.java:499)
	at io.rsocket.kotlin.core.RSocketClientSupport$Config.<init>(RSocketClientSupport.kt:40)
	at io.rsocket.kotlin.core.RSocketClientSupport$Feature.prepare(RSocketClientSupport.kt:61)
	at io.rsocket.kotlin.core.RSocketClientSupport$Feature.prepare(RSocketClientSupport.kt:58)
	at io.ktor.client.HttpClientConfig$install$3.invoke(HttpClientConfig.kt:70)
	at io.ktor.client.HttpClientConfig$install$3.invoke(HttpClientConfig.kt:16)
	at io.ktor.client.HttpClientConfig.install(HttpClientConfig.kt:90)
	at io.ktor.client.HttpClient.<init>(HttpClient.kt:146)
	at io.ktor.client.HttpClientKt.HttpClient(HttpClient.kt:40)
	at io.rsocket.cli.MainKt.buildClient(Main.kt:308)
	at io.rsocket.cli.Main.exec(Main.kt:161)
	at io.rsocket.cli.Main$run$1.invokeSuspend(Main.kt:130)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at io.rsocket.cli.Main.run(Main.kt:129)
	at io.rsocket.cli.Main$Companion.exec(Main.kt:285)
	at io.rsocket.cli.Main$Companion.main(Main.kt:269)
	at io.rsocket.cli.Main.main(Main.kt)
Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: top
	at java.util.concurrent.atomic.AtomicLongFieldUpdater$CASUpdater.<init>(AtomicLongFieldUpdater.java:205)
	at java.util.concurrent.atomic.AtomicLongFieldUpdater.newUpdater(AtomicLongFieldUpdater.java:95)
	at io.ktor.utils.io.pool.DefaultPool.<clinit>(DefaultPool.kt:97)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
	... 39 more
Caused by: java.lang.NoSuchFieldException: top
	at java.lang.Class.getDeclaredField(DynamicHub.java:2411)
	at java.util.concurrent.atomic.AtomicLongFieldUpdater$CASUpdater.<init>(AtomicLongFieldUpdater.java:202)
	... 43 more
```

**Comment by yschimke** [comment]
Haven't found a good workaround.  Reproducible here https://github.com/yschimke/rsocket-cli/tree/kotlin2

**Comment by yschimke** [comment]
Fixed with reflect-config.json entry

```
  {
    "name": "io.ktor.utils.io.pool.DefaultPool",
    "fields" : [ { "name" : "top", "allowUnsafeAccess" : true } ]
  }
```
